### ISSUE TITLE
Missing libXss for ds9

### ISSUE THREAD

**Issue by jehturner** [astroconda/astroconda-contrib#131]
AstroConda's ds9 fails on a CentOS 7 machine because libXss.so.1 is not found. In Ureka, we included that library in Ureka/python/lib. AstroConda's ds9 build should probably just copy /usr/lib64/libXss.so.1 from the build machine into $PREFIX/lib on Linux (as for the 32-bit libs I'm copying to $PREFIX/lib32, for X11IRAF and ECL).

DS9 is also linked to other X11 libraries that we could bundle for portability, but in practice I believe libXss is the only one we have run into that is missing on some systems (in theory, I think libXau, libdmcp & libexpat are also not guaranteed to be present, whereas libX11, libXext, libXft, libXrender, libz, libfontconfig & libfreetype are part of the LSB and in some cases Anaconda too).

**Comment by jhunkeler** [comment]
Packaging shared libraries directly from the build system so binaries will work out of the box for the sake of convenience has always irked me about Ureka, and just in general. There's no way to track them, and they tend to change over time without us knowing it (per build) or not at all (packages that have been built long ago). 

We could maintain a list of packages that require something we don't provide ourselves. Obviously maintaining a X11 stack would be heinous and/or cumbersome, but we can certainly tell users, "In order to use package X you must have Y and Z installed. Please use apt-get, dnf, yum, pacman, port, brew [or whatever] to obtain the appropriate dependencies".

I say this because we continue to get tickets about Ureka's ancient X11 libraries breaking on modern Linux systems. The workaround has always been to delete the Ureka-provided library and let the program pick up the system's version. I'd rather tell a person, "Your version of X11 is too old/new" than "Our version of X11 is too old/new".

IRAF's 32-bit requirements are trickier to handle and I err on the side of "I don't care just do it", simply because it's a serious pain for the user -- but for general packages -- I really prefer to avoid doing stuff like this.

CCs (if you have any thoughts)
@stsci-hack 
@justincely

**Comment by jehturner** [comment]
That's quite understandable. Dumping binaries into the distribution (including ds9, for that matter) is generally objectionable -- but as you say, it's not reasonable to maintain an X11 stack, nor does Anaconda provide one. I've debated this issue in the past with Mark and he told me (roughly) that these ancient X11 interfaces don't really change, so he did not expect a compatibility problem between OS versions (whereas the server's library versions are always the right ones to use with code compiled there). I should re-check those Ureka tickets, but is it really Ureka's X11 libraries that are incompatible with the OS version of X11? Perhaps that's due to a build dependency changing or something? That would be annoying.

The thing is, ds9 is one of the most heavily-used programs in AstroConda and breaks in an obscure way on machines with no libXss, whereas if you just copy that file into the distribution (well, not _quite_; see my next comment), the problem goes away in all the cases I have seen to date. It has been a goal both for Ureka (explicitly) and Anaconda (by inference) to have everything work out of the box, without requiring non-standard OS dependencies or admin privileges (even if it's hard to do much about missing 32-bit loaders for IRAF). When a user just wants to display an image now in the usual way, it's a major overhead to report what seems like a meaningless error to the helpdesk and wait several days for a solution, or to wait for an admin to install something for them. That latency is part of the problem were originally trying to overcome. The user is fairly likely to give up, curse AstroConda as obviously broken and use another machine or something IMO.

Still, if you've been repeatedly advising people to delete libraries bundled with Ureka, that's obviously its own problem (sigh)...

**Comment by jehturner** [comment]
When I say "not quite", we have found in the past that patchelf breaks ds9's strange, self-extracting zip file structure, so you couldn't actually update its RPATH / RUNPATH to find dependencies in the distribution. We therefore had to write a wrapper script that sets LD_LIBRARY_PATH (just for ds9). I'm not sure off hand why you appear not to have run into this (looking at your recipe) -- perhaps because conda sees that none of its dependencies are installed in lib/ and skips updating the RPATH?

**Comment by jehturner** [comment]
However you did it (maybe it has something to do with the short string value), your ds9 has a working relative RPATH, so my last comment is probably a non-issue -- libXss.so.1 should be found as long as it's present in lib/, without doing anything special.

I notice that SAO's latest ds9 binaries (v7.5) are linked against fewer X11 libraries, with no libXss (whereas their archived ds9.linux.7.4.tar.gz does use libXss), so maybe this has been solved upstream and we can get rid of the problem simply by updating to the latest minor ds9 release?

**Comment by jehturner** [comment]
I rebuilt the conda package with DS9 v7.5 and it was still linked to libXss, so that's not just a version difference -- Bill must be doing something differently from his build instructions for CentOS...

In fact, I seem to have figured out the magic incantation to make ds9 build without libXss, which (assuming there are no problems in testing) should resolve both Joe's concerns and mine. (Apparently the libXss dependency was added to Tk about 10 years ago to allow detecting GUI user inactivity, which is unlikely to be something that ds9 depends on, especially given that it builds without it.) More tomorrow.

**Comment by jehturner** [comment]
Submitted PR #150 to fix this and update the version to 7.5 while we're at it.

**Comment by jehturner** [comment]
I notice this recipe seems to build against the OS versions of libs like freetype, zlib etc. but then edits ds9's RPATH to look for Anaconda's versions. It might be safer to set LD_LIBRARY_PATH in the recipe and build against the known run-time versions?

Just for the record, it looked like both Debian and Fedora have patched ds9 to use their OS Tcl/Tk, instead of bundling them in the self-extracting zip as SAO does. The same thing would probably work with Anaconda if needed, but of course the main thing is just that it works (which I think it does now).

**Comment by jhunkeler** [comment]
Yeah, if it works and isn't hurting anyone I think we should leave it alone. :)


I'd prefer to avoid `LD_LIBRARY_PATH` at all costs, however the core problem is, conda-build makes no effort to enforce pkg-config usage or setting up LDFLAGS/CFLAGS/xyzFLAGS to point back to its own `$CONDA_PREFIX/lib`, so image linkage tends to end up all over the place. Continuum gets around it by resetting the linkage post-build. I'm not a huge fan of this either but it's what they do. Trust me -- I've found missing symbols in stupid places (i.e. their broken readline package) that were obviously not missing at compile-time.

Adding pkg-config as a dependency, setting `PKG_CONFIG_PATH=$CONDA_PREFIX/lib` in the build script and tweaking makefiles/flags to fixup the linkage usually works (for most packages... probably not for DS9 without extreme patching).

I didn't bother with any of this because it's a total nightmare to unhook all of its internal deps and could end up requiring tons of maintenance in the future to keep it running. Fedora completely dropped DS9 in 2011 due to broken system dependencies. Well, it's more like DS9 required older versions of packages Fedora was no longer willing to hold back for the sake of a single binary. 

https://src.fedoraproject.org/cgit/rpms/ds9.git/refs

And in 2014 dropped building it on RHEL/EPEL for the same reasons.

**Comment by jehturner** [comment]
OK, sounds like you have a better method that might avoid fighting with pkg-config in general. I was only suggesting using LD_LIBRARY_PATH in the build script though, not at run time. Yes, Continuum does seem to handle some of these engineering issues much more haphazardly than you would expect for their level of ambition and funding...

(FYI, I did set LD_LIBRARY_PATH in the iraf.axe build since conda wasn't taking care of it; that explains your previous comment about pkgconfig as a dependency)
