### ISSUE TITLE
stsci metapackage has Astropy conflict between calcos and glue

### ISSUE THREAD

**Issue by pllim** [astroconda/astroconda-contrib#200]
**From a help call**

User needs to downgrade Astropy for `calcos` to run but is prevented from doing so by Glue.

```
$ conda create -n cos python=3 stsci
$ source activate cos
$ conda install astropy=1.2.1
Fetching package metadata ...........
Solving package specifications: .
 UnsatisfiableError: The following specifications were found to be in conflict:
   - astropy 1.2.1*
   - glue-core -> astropy >=1.3 -> numpy 1.12*
 Use "conda info <package>" to see the dependencies for each package.
```

**Comment by jhunkeler** [comment]
`stsci` provides almost everything we produce. The data analysis toolset uses glueviz so that's why it's being installed automatically.

Each versioned release of `stsci` maintains a particular floor version on certain packages to "help" prevent downgrade breakage (i.e. `astropy >=1.1`). Of course, as time moves forward and packages start to evolve, some recipes may impose their own floor limits thus overriding `stsci`'s control over the minimum version allowed -- which is the case here.

The latest version of `glueviz` (and friends) strictly require `astropy >=1.3`, so downgrading is impossible as long as that package is present in the environment.

The workaround is as follows:
```
# X=python_major
# Y=python_minor

$ conda create -n cos python=X.Y astropy=1.2.1 calcos
$ source activate calcos
```

If `calcos` had been updated to be compatible with `astropy >=1.3` when we did our initial sweep months ago this would be a non-issue right now.

**Comment by pllim** [comment]
The underlying problem is right now `stsci` has conflicting package requirements. I propose we excluded `calcos` until they bother to update their codes.

**Comment by pllim** [comment]
@stscirij , when is calcos going to be updated?

**Comment by jhunkeler** [comment]
`stsci` doesn't have conflicting requirements; the predefined floors are correct over there. The packages (`calcos`) that are not kept in sync with the rest of the toolchain are causing the conflict. 

If we removed `stsci-data-analysis` from the `stsci` metapackage then the problem will stop. `glue-core` will pretty much disappear from the map, but I'm not convinced that's what we want. What we need is an update to calcos.

**Comment by stscirij** [comment]
I agree that calcos needs to be updated.  But the team don't want the version in astroconda to be different from what's run in the pipeline.  When we deliver the new version for DMS 2017.2, we can update the version of calcos in astroconda so that it runs with the current versions of astropy and numpy.  I'm not sure what the timeline for that is, I'll ask the team.

  Users who want to run calcos should use the pipeline stack in astroconda for DMS 2016.2.  We should probably update the astroconda compatibility page to inform users that if they want to use calcos they will have to use the pipeline stack until we deliver a new version, i.e. the option of downgrading astropy to version 1.2.1 doesn't work any more.

  Robert J.

________________________________

**Comment by jhunkeler** [comment]
For anyone landing here in the future, @stscirij is referring to: http://astroconda.readthedocs.io/en/latest/releases.html#id2

**Comment by pllim** [comment]
Oh, issue number 200! 🎉

**Comment by jhunkeler** [comment]
@pllim This should be resolved now that the version floors have been adjusted. Can you confirm?

**Comment by pllim** [comment]
I'm afraid we'll have to reopen this very soon. Astropy 2.0 came out today.

**Comment by jhunkeler** [comment]
Hmm.
Wouldn't we have already seen the devastating effects of 2.0 in 'dev' tests by now?

**Comment by pllim** [comment]
No, because CALCOS is not tested in our pandokia system. I think COS Team tests it themselves.

**Comment by pllim** [comment]
Let's close this for now. I'll open another one if we run into this again with a different Astropy version.
