### ISSUE TITLE
Stuck on solving environment

### ISSUE THREAD

**Issue by jazamatazz** [astroconda/astroconda-contrib#714]
Trying to install astroconda, keeps getting stuck on solving environment. I tried "conda update --all" and it did not help.
![Screenshot from 2021-04-14 13-31-58](https://user-images.githubusercontent.com/68238960/114753957-08fc4280-9d26-11eb-9ba0-874dc093e8be.png)

**Comment by jhunkeler** [comment]
Try specifying a version of Python alongside the `stsci` metapackage. At the moment 3.6 and 3.7 are the only two that will work. Infinite solving problem is because your base environment is probably newer (3.8 or 3.9), so the solver is unable to solve for something that don't exist (instead of just recognizing immediately that they're not there.) 

AstroConda does not produce packages for 3.8 or 3.9.

```bash
$ export PATH=~/anaconda3/bin:$PATH
$ conda create -n astroconda python=3.7 stsci
```

Let me know if that helps at all.

**Comment by jazamatazz** [comment]
sorry for never writing back! yes that did work, thank you!
