### ISSUE TITLE
Installing notebook with astroconda

### ISSUE THREAD

**Issue by mgennaro** [astroconda/astroconda-contrib#76]
Hi,
I was wondering whether it would be possible to install the notebook package by default with astroconda.
I find it would be more practical than finding out that "jupyter notebook" doesn't work at first, and that notebook must be installed separately.

Thanks,
Mario

**Comment by pllim** [comment]
```
conda create -n astroconda stsci jupyter notebook
```

**Comment by mgennaro** [comment]
Thanks Pey Lian,
however I thought that jupyter gets installed even without specifiying it, that's why I wondered, why is notebook not?

I get I can use your command, but I have just reinstalled astroconda on a new machine, and I had forgotten that the notebook is missing. So I forgot to include it explicitly in my creation command.
Then when I realized the problem, I had to install it separately.

I am not the only one who's had this issue. I had to show at east one other person that "notebook" is a separate package and needs to be installed separately from jupyter.
Of course this is no big deal, but any "non expert" may find it confusing that jupyter is there but notebook isn't, so why is it that they are not both installed by default?

Mario

**Comment by jhunkeler** [comment]
This question has been raised in the past (outside of github). Our previous stance on this type of request was:

If we don't depend on it don't include it.

I think since Jupyter (and the use of notebooks) has gained traction in the community we should consider adding it. @astroconda/maintainers @pllim Does anyone object to incorporating the following dependencies to the main `stsci` metapackage? 

```
    entrypoints:      0.2.2-py35_0
    ipykernel:        4.5.0-py35_0
    ipython:          5.1.0-py35_0
    ipython_genutils: 0.1.0-py35_0
    jsonschema:       2.5.1-py35_0
    jupyter_client:   4.4.0-py35_0
    jupyter_core:     4.2.0-py35_0
    libsodium:        1.0.10-0
    mistune:          0.7.3-py35_0
    nbconvert:        4.2.0-py35_0
    nbformat:         4.1.0-py35_0
    notebook:         4.2.3-py35_0
    path.py:          8.2.1-py35_0
    pexpect:          4.0.1-py35_0
    pickleshare:      0.7.4-py35_0
    prompt_toolkit:   1.0.3-py35_0
    ptyprocess:       0.5.1-py35_0
    pyzmq:            16.0.0-py35_0
    simplegeneric:    0.8.1-py35_1
    terminado:        0.6-py35_0
    tornado:          4.4.2-py35_0
    traitlets:        4.3.1-py35_0
    wcwidth:          0.1.7-py35_0
    zeromq:           4.1.5-0
```

**Comment by pllim** [comment]
I don't use notebook that much myself, so in principle I disagree that we should include notebook by default. Then we might have the opposite request like "why is this package taking up my disk space, can you not install it by default?". It is not that hard to install as needed, so would it be easier to just add documentation to install it instead of actually installing it?

**Comment by mgennaro** [comment]
My point was:
"why is jupyter included while notebook is left out?"
To me, non expert, average user, the two always seemed to go together. However, from what @pllim is saying I guess that there could be a use for jupyter even without notebook, I didn't know about that (or maybe is just some dependencies that need to be satisfied that led you to include jupyter in astroconda, as @jhunkeler was hinting at).

Maybe asking the community (of users, not of developers) could help you understand whether notebook could be a valued addition to astroconda or not.
Mario

**Comment by justincely** [comment]
@pllim I think for some of these meta-pacakges, we want to treat them a little differently than just tracking dependencies.  In some cases, it can be very useful to provide a suite of the tools a user will be likely to need. Additionally, some of our products are very notebook-focused, so it makes sense to me to include it in our default distribution.

@jhunkeler, i would argue that we should add notebook and its deps to the data-analysis subpackage instead.  That would still include them if someone did a global STSCI install, but keep them separate out of the pipelines and things which have less use for them.  

Thoughts?

**Comment by pllim** [comment]
Ops. Commented in the wrong issue [here](https://github.com/astroconda/astroconda-contrib/issues/77#issuecomment-256368388).

**Comment by justincely** [comment]
@jhunkeler just added notebook as a dependency to imexam, so stsci-data-analysis (and by extension the entire stsci package) will now install notebook as well.  

My opinion would be to keep it this way: making sure notebook comes as part of the stsci-data-analysis package.  This would mean that anyone doing the global install will get it, but people doing targeted installs of the pipelines wouldn't - which is a desired behavior since the notebooks aren't necessary for running the pipelines.

@mgennaro would that satisfy your use-case?

**Comment by mgennaro** [comment]
@justincely 
Yes, thanks a lot, I think that many will benefit from this addition: while we were discussing the issue an other person asked me why their .ipynb files would not open, and I had to tell them that notebook wasn't installed in astroconda by default.

**Comment by justincely** [comment]
absolutely, thanks for the suggestion!
